### ISSUE TITLE
could I know why set "--srv No" for busted model, thanks

### ISSUE THREAD

**Issue by liamxg** [veg/selection-tutorial#4]
`hyphy busted --srv No --alignment data/HIV-sets.nex --starting-points 5 --output results/HIV-sets.nex.BUSTED.json`

**Comment by stevenweaver** [comment]
`No` is the default BUSTED as specified in the [original paper](https://academic.oup.com/mbe/article/32/5/1365/1134918). SRV is an extension that accounts for synonymous rate variation specified in a [later paper](https://academic.oup.com/mbe/article/37/8/2430/5739973).

**Comment by stevenweaver** [comment]
Not sure. I didn't write it.

**Comment by stevenweaver** [comment]
`Yes` is a more conservative test that accounts for synonymous rate variation. It would be difficult to expand much more beyond the Discussion in [the BUSTED SRV paper](https://academic.oup.com/mbe/article/37/8/2430/5739973?login=false#206122992) without a more specific question regarding it.

**Comment by stevenweaver** [comment]
The comment powerfully recommends including SRV in your analyses.

```
The empirical and simulation work in this paper adds to a growing body of literature strongly suggesting that the models underlying these methods—not only BUSTED, but almost certainly any positive selection method that assumes the absence of SRV—are importantly wrong and need to be revised.
```
